CREATE TABLE recommendation (
  ID int(11) NOT NULL AUTO_INCREMENT,
  RECOMMENDER_ID int(11) NOT NULL,
  COMPANY_ID int(11) NOT NULL,
  START_PRICE double NOT NULL,
  TARGET_PRICE double NOT NULL,
  DURATION bigint(20) DEFAULT NULL,
  RECOMMENDATION_STATUS varchar(20) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  CREATED_DTS bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE company (
  ID int(11) NOT NULL AUTO_INCREMENT,
  PAID_UP_VALUE int(11) NOT NULL,
  ISIN_NUMBER varchar(20) NOT NULL,
  SYMBOL varchar(20) NOT NULL,
  NAME_OF_COMPANY TINYBLOB NOT NULL,
  SERIES varchar(10) NOT NULL,
  MARKET_LOT int(11) NOT NULL,
  FACE_VALUE int(11) NOT NULL,
  CREATED_DTS bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE recommender (
  ID int(11) NOT NULL AUTO_INCREMENT,
  RECOMMENDED_BY_ID int(11) NOT NULL,
  FB_ID varchar(20) DEFAULT NULL,
  FIRST_NAME TINYBLOB(20) DEFAULT NULL,
  LAST_NAME TINYBLOB DEFAULT NULL,
  WEBSITE_URL TINYBLOB DEFAULT NULL,
  RECOMMENDER_TYPE varchar(20) NOT NULL,
  CREATED_DTS bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE recommender (
  ID int(11) NOT NULL AUTO_INCREMENT,
  RECOMMENDED_BY_ID int(11) NOT NULL,
  FB_ID varchar(20) DEFAULT NULL,
  FIRST_NAME TINYBLOB(20) DEFAULT NULL,
  LAST_NAME TINYBLOB DEFAULT NULL,
  WEBSITE_URL TINYBLOB DEFAULT NULL,
  RECOMMENDER_TYPE varchar(20) NOT NULL,
  CREATED_DTS bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE user (
  ID int(11) NOT NULL AUTO_INCREMENT,
  FB_ID varchar(20) DEFAULT NULL,
  FIRST_NAME TINYBLOB(20) DEFAULT NULL,
  LAST_NAME TINYBLOB DEFAULT NULL,
  CREATED_DTS bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
