CREATE TABLE notification (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(64) DEFAULT NULL,
  PHONE_NUMBER varchar(20) DEFAULT NULL,
  EMAIL_ADDRESS varchar(64) DEFAULT NULL,
  VEHICLE_NUMBER varchar(45) NOT NULL,
  SERVICE_TYPE varchar(45) NOT NULL,
  NOTIFICATION_STATUS varchar(20) NOT NULL,
  IS_REPEAT TINYINT(1) NOT NULL,
  CREATED_DTS bigint(20) DEFAULT NULL,
  NOTIFICATION_DTS bigint(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY `VEHICLE_NUMBER_UNIQUE` (`VEHICLE_NUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;